app: # 应用基本配置
  env: dev # 环境名称
  port: 8082 # 服务监听端口号
  name: gp-templte # 应用名称

database:
  driver: mysql # 数据库驱动
  host: 127.0.0.1 # 域名
  port: 3306 # 端口号
  database: go_template # 数据库名称
  username: root # 用户名
  password: root # 密码
  charset: utf8mb4 # 编码格式
